# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

formats:
  - pdf
  - epub

# Build documentation with MkDocs
mkdocs:
  configuration: mkdocs.yml

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11" 
  jobs:
    post_create_environment:
      # Install uv
      - pip install uv
      # Tell uv to not use a virtual environment
      - UV_PROJECT_ENVIRONMENT=$READTHEDOCS_VIRTUALENV_PATH
    post_install:
      # Install dependencies with 'docs' dependency group
      - uv sync --group docs
