site_name: python-wiremock docs
theme:
  name: readthedocs
  highlightjs: true
plugins:
  - search
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition

nav:
  - Home: index.md
  - Quickstart Guide: quickstart.md
  - Installation: install.md
  - Testcontainers: testcontainers.md
  - Standalone: api-client.md
  - Resources:
    - Changelog: changelog.md
