site_name: python-wiremock docs
theme:
  name: readthedocs
  highlightjs: true
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_submodules: true
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition

nav:
  - Home: index.md
  - Quickstart Guide: quickstart.md
  - Installation: install.md
  - Testcontainers: testcontainers.md
  - Standalone: api-client.md
  - Reference: reference.md
  - Contributing: CONTRIBUTING.md
  - Resources:
    - Examples: examples.md
    - Changelog: changelog.md
