name: Release Drafter

on:
  push:
    branches:
      - master

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Get version from pyproject.toml
        run: echo "VERSION=$(uv version --short)" >> $GITHUB_ENV
      - uses: release-drafter/release-drafter@v5
        with:
          name: ${{ env.VERSION }}
          tag: ${{ env.VERSION }}
          version: ${{ env.VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
